name: Add contributors
on:
  schedule:
    - cron:  '20 20 * * *'
  push:
    branches: 
      - main

jobs:
  Weather-Predictor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Prithvi2310/Weather-Predictor@main
      with:
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '6'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'
